datashim-io/datashim

examples/templates/example-dataset-host.yaml
src/dataset-operator/pkg/controller/dataset/dataset_controller.go

This PR adds the ability of creating Datasets out of a path in the host machine(s)

Dataset hostpath

---

examples/noobaa/noobaa_install.sh

fixes for correct waits and warning about k8s version

---

src/csi-driver-nfs/chart/templates/csi-nodeplugin-rbac.yaml

Fix helm chart typo on csi-nodeplugin-rbac

---

src/dataset-operator/pkg/controller/dataset/dataset_controller.go

This PR introduces the functionality discussed in #68

introduce cache.disabled and cache.plugin labels

---

docs/Archive-based-Datasets.md

Archive instructions are still pointing to the old archive branch and it confuses some of our users. Updating the docs to be more present.

Update archive instructions

---

src/dataset-operator/pkg/controller/dataset/dataset_controller.go

This PR updates appropriately the status of a Dataset when the Name contains invalid characters

Dataset Name invalid characters

---

plugins/ceph-cache-plugin/deploy/rook/toolbox.yaml

This PR updates the toolbox.yaml of rook to the latest 1.5 release

Rook 1.5 toolbox

---

src/dataset-operator/pkg/admissioncontroller/mutate.go

This printf doesn't explain anything (thought it is thankfully unique so it was easy to find ;))

Remove unclear printf

---

.github/workflows/ci.yml

Signed-off-by: Srikumar Venugopal <srikumarv@ie.ibm.com>

upgrading Ubuntu to fix pipenv update

---

src/csi-s3/cmd/s3driver/Dockerfile.full

closes #192 
Signed-off-by: Srikumar Venugopal <srikumarv@ie.ibm.com>

Changing image from distroless to alpine

---

src/generate-keys/script.sh

Fixes #210 
Signed-off-by: Alessandro Pomponio <alessandro.pomponio1@ibm.com>

Extend webhook certificate duration to 10000 days, cleanup script

---

src/generate-keys/Dockerfile
src/generate-keys/script.sh

fix: ensure generate_keys works on all architectures

---

.github/workflows/testing.yml
ci/configure-minio.yaml
ci/minio.yaml
ci/s3.yaml

This PR addresses issue #222 by replacing NooBaa with MinIO

ci: use MinIO instead of NooBaa

---

README.md

This PR modifies the README to include `kind` in the install options.

Updated documentation to mention kind in install options

---

chart/Chart.yaml

Renamed helm chart to `datashim-charts`

Renamed helm chart to datashim-charts

---

chart/values.yaml
src/csi-driver-nfs/chart/templates/csi-attacher-nfsplugin.yaml
src/csi-driver-nfs/chart/templates/csi-nodeplugin-nfsplugin.yaml
src/csi-driver-nfs/chart/values.yaml
src/csi-s3/chart/templates/attacher.yaml
src/csi-s3/chart/templates/csi-s3.yaml
src/csi-s3/chart/templates/provisioner.yaml
src/csi-s3/chart/values.yaml

Added affinity options to charts for multi-cluster deployment cases (win + linux) 
fixes #329

Added affinity option to helm charts

---

src/dataset-operator/controllers/datasetinternal_controller.go

logging error when secret is missing

---

.github/workflows/ci.yml

Should fix Action interpreting 3.10 as 3.1
https://github.com/datashim-io/datashim/actions/runs/10039526174/job/27743655853#step:3:23

fix: quote python version

---

.github/workflows/ci.yml

restored the copy clause to prevent overwriting of helm index

---

.github/workflows/push-updated-images.yml
.github/workflows/release.yml
src/cos-uploader/build_multiarch_cos_uploader.sh
src/dataset-operator/controllers/archive_handler.go

Note: the `amazon/aws-cli` image is not available for `ppcle64`, so it hasn't been included

fix: build cos-uploader for amd64 and arm64

---

.github/workflows/push-updated-csi-plugins.yml

ci: new action for pushing CSI images
