datashim-io/datashim

- src/csi-driver-nfs/deploy/kubernetes/csi-attacher-nfsplugin.yaml
- src/csi-driver-nfs/deploy/kubernetes/csi-attacher-rbac.yaml
- src/csi-driver-nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
- Updated Service account names to avoid warnings while uninstalling
- Pull secret is now injected ad deployment time
Signed-off-by: Christian Pinto <christian.pinto@ibm.com>
> csi-nfs-driver deployment updates

- release-tools/Makefile
- release-tools/generate-keys.sh
- src/dataset-operator/deploy/webhook.yaml.template
Certificates for the webhook were generated with a fixed namespace name. This is now decided at installation time.
Fixed also the name of the webhook to something more related to this project.
> Keys creation fix

- Makefile
- src/csi-driver-nfs/deploy/kubernetes/csi-attacher-rbac.yaml
Modifies cluster role `external-attacher-runner-nfs` to have `patch` permissions for resource `volumeattachments.storage.k8s.io`
> Fix to allow external-attacher-nfs to attach a volume

- plugins/ceph-cache-plugin/deploy/operator.yaml
- plugins/ceph-cache-plugin/deploy/role.yaml
- plugins/ceph-cache-plugin/pkg/controller/dataset/ceph_related_objects.go
This patch supports setting the NodeAffinity of the rgw pod (in general, can be used by any future caching mechanisms), spawned on-the-fly by DLF, to the node with a hostname that matches the label `cache.hostname`. Furthermore, to accommodate any changes to the nodes of the k8s cluster that may result in a pending rgw if a node with the specified hostname does not exist, this patchset firstly checks if the respective node exists and only then assigns the NodeAffinity of the rgw pod.
> Introduce cache.hostname label in dataset

- src/csi-s3/cmd/s3driver/Dockerfile.full
As pointed by [this issue](https://github.com/kahing/goofys/issues/357) vanilla goofys sources exhibit the following issue when run on ppc64le architecture
```
panic: Page size is unexpectedly 65536
goroutine 1 [running]:
github.com/jacobsa/fuse/internal/buffer.init.0()
/go/pkg/mod/github.com/kahing/fusego@v0.0.0-20200327063725-ca77844c7bcc/internal/buffer/in_message.go:33 +0xbc
```
After some commits on the goofys master this issue resurfaced for ppc64le. This PR is applying the latest fixes to fix this behavior of goofys on ppc64le
> [ppc64le] goofys fixes

- chart/templates/namespace.yaml
To install helm chart with helm3, it fails with following error
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "dlf" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "dataset-lifecycle-framework"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dlf"
```
To install with creating namespace with helm3, you can run `helm install --create-namespace`
> remove namespace from helm chart

- src/csi-s3/pkg/s3/mounter_goofys.go
Added a line in `mounter_goofys.go` to set up a specified region. According to documentation goofys sets a default region (default: "us-east-1"). From now, region should be considered as mandatory argument so it would be either "" or defined. This PR regards #67 .
> s3/mounter_goofys: added region

- examples/templates/example-dataset-s3-provision.yaml
- plugins/ceph-cache-plugin/pkg/controller/dataset/dataset_controller.go
- src/csi-s3/pkg/s3/config.go
- src/csi-s3/pkg/s3/controllerserver.go
- src/csi-s3/pkg/s3/s3-client.go
- src/dataset-operator/pkg/controller/dataset/dataset_controller.go
- src/dataset-operator/pkg/controller/datasetinternal/datasetinternal_controller.go
This PR introduces ```provision``` flag in the Dataset Spec. At the moment DLF, in the case of a COS type dataset, creates the bucket automatically if it does not exist on the remote COS. With the provision flag (default value is false) in this PR, the aforementioned behaviour changes and only when the user explicitly specifies ```provision: true```, inside the spec of the Dataset, DLF will create the bucket if it does not exist on the remote COS.
> Implement Provision field in DatasetSpec

- examples/templates/example-dataset-s3-secrets.yaml
- examples/templates/example-s3-secret.yaml
- src/dataset-operator/pkg/controller/datasetinternal/datasetinternal_controller.go
Adding functionality to supply auth info for S3/COS datasets using secrets
Instead of:
` accessKeyID: "{AWS_ACCESS_KEY_ID}"`
` secretAccessKey: "{AWS_SECRET_ACCESS_KEY}"`
the user can provide:
`secret-name: "{SECRET_NAME}"`
`secret-namespace: "{SECRET_NAMESPACE}"` 
secret-namespace is optional if the secret is defined in the same namespace as the dataset
> Initial support for secrets for object storage datasets

- plugins/ceph-cache-plugin/deploy/rook/cluster-on-pvc.yaml
- plugins/ceph-cache-plugin/deploy/rook/cluster.yaml
- plugins/ceph-cache-plugin/go.mod
- plugins/ceph-cache-plugin/go.sum
- plugins/ceph-cache-plugin/pkg/controller/dataset/ceph_related_objects.go
- plugins/ceph-cache-plugin/pkg/controller/dataset/dataset_controller.go
DLF with the latest commits can [provision the bucket](https://github.com/IBM/dataset-lifecycle-framework/commit/adf231669a67a0b419f862cac3b5f37467c4ffb4) and remove it as well with [remove-on-delete](https://github.com/IBM/dataset-lifecycle-framework/commit/103f14ae28eeca3b28f0af6c2279b54f4a986d6c). This PR aligns our CEPH caching plugin with the aforementioned features and also propagates properly the ```region``` of the Dataset to the CEPH caching plugin.
> Align our CEPH Caching plugin with the latest DLF features

- release-tools/manifests/dlf-arm64.yaml
- release-tools/manifests/dlf-ibm-k8s.yaml
- release-tools/manifests/dlf-ibm-oc.yaml
- release-tools/manifests/dlf-oc.yaml
- release-tools/manifests/dlf-ppc64le.yaml
- release-tools/manifests/dlf.yaml
- src/csi-s3/chart/templates/driver.yaml
- src/dataset-operator/chart/templates/apps/webhook-definition.yaml
- src/dataset-operator/chart/templates/crds/com.ie.ibm.hpsys_datasetinternals_crd.yaml
- src/dataset-operator/chart/templates/crds/com.ie.ibm.hpsys_datasets_crd.yaml
This PR update the following deprecated `apiVersion` into Helm charts:
- storage.k8s.io/v1beta1 -> storage.k8s.io/v1
- admissionregistration.k8s.io/v1beta1 -> admissionregistration.k8s.io/v1
- apiextensions.k8s.io/v1beta1 -> apiextensions.k8s.io/v1
> Update deprecated apiVersion into Helm charts

- README.md
Fix a typo in readme, letting user to make a bad namespace labelling ,  then  pods labelling functionality was not working
> fix a typo in readme : namespace bad labelling

- src/dataset-operator/pkg/controller/dataset/archive_handler.go
In the newer version of aws command and S3 server, S3 bucket needs to be create with an separate S3 API since the `aws s3 cp` command no longer creates a new bucket. Below are the quick fixes to make it working.
Ideally we should make these commands configurable via a configmap, so when there's new changes to S3 API, we can update the configmap rather than building a new image every time.
> S3 bucket creation command is missing for archive handler

- plugins/ceph-cache-plugin/deploy/rook/operator.yaml
This PR updates the rook image in the operator.yaml that contains the fix for deleting a user that has an associated bucket.
> Remove RGW and Data leftovers on dataset deletion

- src/csi-s3/pkg/s3/mounter_goofys.go
I am trying to use datashim with a public bucket. And this should work (in theory). 
After digging around I saw that goofys supports this. However contrary to [this commit message](https://github.com/kahing/goofys/commit/bda62d906b8d6dc6499be87705466cb6e2575bf2) it seems that to not use any credentials one can just omit the `--profile` argument and goofys will figure things out.
I tested this change out and things work now if I use empty strings for the credentials (`""`).
closes #131 
For example this manifest will not work before this PR but works after this change:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
name: example-public-dataset
spec:
local:
type: "COS"
accessKeyID: ""
secretAccessKey: ""
endpoint: "http://s3.amazonaws.com"
bucket: "giab"
---
apiVersion: …
```
> fix: use anonymous credentials with goofys

- build-tools/Makefile
- chart/values.yaml
- docs/FAQ.md
- release-tools/manifests/dlf-arm64.yaml
- release-tools/manifests/dlf-ibm-k8s.yaml
- release-tools/manifests/dlf-ibm-oc.yaml
- release-tools/manifests/dlf-oc.yaml
- release-tools/manifests/dlf-ppc64le.yaml
- release-tools/manifests/dlf.yaml
- src/csi-h3/chart/values.yaml
This is a breaking change as any K8s cluster that's older than 1.17 will not be supported by Datashim anymore. Fixes #132 and #129
> Update attachment api to support K8s 1.20+

- src/csi-driver-nfs/chart/templates/csi-attacher-nfsplugin.yaml
- src/csi-driver-nfs/chart/templates/csi-nodeplugin-nfsplugin.yaml
- src/csi-driver-nfs/chart/values.yaml
- src/csi-h3/chart/templates/csi-controller-h3.yaml
- src/csi-h3/chart/templates/csi-nodeplugin-h3.yaml
- src/csi-h3/chart/values.yaml
- src/csi-s3/chart/templates/attacher.yaml
- src/csi-s3/chart/templates/csi-s3.yaml
- src/csi-s3/chart/templates/provisioner.yaml
- src/csi-s3/chart/values.yaml
- src/dataset-operator/chart/templates/apps/operator.yaml
- src/dataset-operator/chart/values.yaml
I noticed that there does not seem to be an option to add tolerations, affinities, etc.
This is definitely useful when you have nodes with taints but when you want the daemonSets (for node plugins) to run on all of your nodes. I could not find in the current state of the code any way to do this.
So I followed how affinities/tolerations/nodeSelectors are added when you create a helm chart with the helm CLI (i.e. `helm create foo`). Unlike the helm CLI template though I did separate things for the DaemonSets and everything else (i.e. controllers/attachers). For example you may want to run the controller on a specific node but the DaemonSet on all nodes (or on more nodes).
Let me know what you think. I am happy to make adjustments.
Signed-off-by: Tasko Olevski <tasko.olevski@sdsc.ethz.ch>
> feat(chart): add nodeSelector, tolerations, affinity

- src/dataset-operator/pkg/admissioncontroller/mutate.go
ensures that the dataset, mount and configmap labels work across both init and normal containers
> Fix #157 pvc mounts in init containers using the dataset labels

- .gitmodules
- examples/scheduling/README.md
- plugins/ceph-cache-plugin/Makefile
This scheduler plugin uses the placement information introduced by #127 to schedule pods close to the gateway for a cached dataset. This is experimental code and only works for caching provided by Datashim's Ceph-cache plugin for object stores.
> Provide example for a scheduler plugin using the placement information given by Datashim

- release-tools/manifests/dlf-arm64.yaml
- release-tools/manifests/dlf-ibm-k8s.yaml
- release-tools/manifests/dlf-ibm-oc.yaml
- release-tools/manifests/dlf-oc.yaml
- release-tools/manifests/dlf-ppc64le.yaml
- release-tools/manifests/dlf.yaml
- src/dataset-operator/chart/templates/apps/operator.yaml
This PR restores the previous dataset-operator binary in the manifests, so that the installation process does not create a dataset-operator failing because of the wrong command
Signed-off-by: Srikumar Venugopal <srikumarv@ie.ibm.com>
> temporary update to manifests to accommodate old images

- .github/workflows/testing.yml
Issue: Currently there is no integration testing set up for Datashim - this means that there could be commits that unexpectedly break the software and that will require someone to notice before any remediation can be taken.
This PR adds a GitHub Action that:
1. Creates a KinD cluster
2. Deploys Datashim on it
3. Deploys NooBaa on it (for a local S3 bucket)
4. Creates a Dataset
5. Creates and runs a Job mounting a Dataset in a container and writing a file
6. Creates and runs a Job mounting a Dataset in a container and reading the file that the previous job created.
This action runs only for the following PR events (ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request):
- `ready_for_review`
- `review_requested`
- `opened`
- `edited`
- `reopened` …
> Create Action for Integration Testing

- src/csi-driver-nfs/chart/templates/csi-attacher-nfsplugin.yaml
- src/csi-driver-nfs/chart/templates/csi-nodeplugin-nfsplugin.yaml
- src/csi-h3/chart/templates/csi-controller-h3.yaml
- src/csi-h3/chart/templates/csi-nodeplugin-h3.yaml
- src/csi-s3/chart/templates/attacher.yaml
- src/csi-s3/chart/templates/csi-s3.yaml
- src/csi-s3/chart/templates/provisioner.yaml
- src/dataset-operator/chart/templates/apps/operator.yaml
This PR adds:
- a way to specify `priorityClassName` (either per plugin or globally)
- a way to configure [Cluster Autoscaler DaemonSet eviction setting](https://github.com/kubernetes/autoscaler/blob/5d3ad0c/cluster-autoscaler/FAQ.md#how-can-i-enabledisable-eviction-for-a-specific-daemonset) (either per plugin or globally)
Both of these configs can help to prevent Kubernetes or Cluster Autoscaler from evicting Datashim plugins pods before workload pods that may rely on it to work properly.
> Adds priorityClassName and cluster autoscaler daemonset eviction to charts

- .github/workflows/testing.yml
Fixes #227 
To test this PR we can run the following after having built the images for the `dataset-operator` and `generate-keys`:
```bash
kind create cluster
sed -i 's/Always/Never/g' release-tools/manifests/dlf.yaml
kind load docker-image quay.io/datashim-io/dataset-operator:latest
kind load docker-image quay.io/datashim-io/generate-keys:latest
make deployment
```
The results will be:
```text
oc get pods -n dlf
NAME                                READY   STATUS              RESTARTS   AGE
csi-attacher-nfsplugin-0            0/2     ErrImageNeverPull   0          8s
csi-attacher-s3-0                   0/1     ErrImageNeverPull   0          8s
csi-nodeplugin-nfsplugin-m5qtd      1/2     ErrImageNeverPull   0          8s
csi-provisioner-s3-0                0/1     ErrImageNeverPull   0 …
```
> ci: import built images in KinD cluster to avoid pulling remotes

- src/generate-keys/script.sh
> regression: fix missing env vars in generate-keys/script.sh

- .github/workflows/testing.yml
this change sets up the S3 backend storage (currently, MinIO) before installing Datashim in the CI script
> ci: Setup pre-requisites before installing Datashim

- examples/templates/example-pod-mult-useas.yaml
- src/dataset-operator/admissioncontroller/mutatingwebhook.go
- src/dataset-operator/admissioncontroller/mutatingwebhook_test.go
Fixes #271
BY merging this PR, the following pod definition
```
apiVersion: v1
kind: Pod
metadata:
name: busybox
labels:
app: busybox
dataset.0.id: "tests3a"
dataset.0.useas: "mount.configmap"
```
will lead to a pod definition like below:
```
apiVersion: v1
kind: Pod
metadata:
...
spec:
containers:
...
envFrom:
- configMapRef:
name: tests3a
prefix: tests3a_
- prefix: tests3a_
secretRef:
name: tests3a
...
volumeMounts:
...
- mountPath: /mnt/datasets/tests3a
name: tests3a
...
volumes:
...
- name: tests3a
persistentVolumeClaim:
claimName: tests3a
```
> feat: support multiple useas modes

- src/dataset-operator/admissioncontroller/mutatingwebhook.go
- src/dataset-operator/admissioncontroller/mutatingwebhook_test.go
- src/dataset-operator/testing/wrapper.go
- src/generate-keys/webhook.yaml.template
Fixes #287
This PR fixes the issue raised in #287 by:
1. Updating the webhook configuration to only apply to delete
2. Adding extra checks to NOT issue patches for `useas: configmap` if the dataset duplicates the name of an existing configmap
tested with `kubectl edit` on `spec.image` for an existing pod with a dataset injected as a `configmap` and has no issues
> Block webhook from mutating on pod updates

- src/dataset-operator/admissioncontroller/mutatingwebhook.go
- src/dataset-operator/controllers/datasetinternal_controller.go
- src/dataset-operator/go.mod
Fixes #269 
Ensures that `readonly: true` in Dataset specification is carried through to the mounting of buckets inside the container
Note: this is tested for `csi-s3` backend only. We will need to check other CSI backends to see if the spec is being followed
> fix: Ensure S3 buckets are mounted with the right access permissions

- .github/workflows/release.yml
- build-tools/Makefile
- build-tools/helpers.mk
- chart/Chart.yaml
- src/dataset-operator/build_and_push_multiarch_dataset_operator.sh
- src/dataset-operator/build_dataset_operator.sh
- src/dataset-operator/go.mod
- src/dataset-operator/go.sum
Adds a new action for creating a release when a tag is pushed to the repo. The action will
1. Build images for the operator and key generator with the given tag
2. Build images for the included CSI plugins (S3, NFS)
3. creates a Helm chart that is hosted in the project github pages
4. makes a Github release
Fixes #259
> feat: Action for automatic release

- .github/workflows/release.yml
- src/csi-driver-nfs/Dockerfile
- src/csi-driver-nfs/build_and_push_multiarch_csinfs.sh
- src/csi-s3/build_and_push_multiarch_csis3.sh
- src/csi-s3/cmd/s3driver/Dockerfile.full
Changes the CSI Plugin build pipeline to entirely use `docker buildx` instead of the complicated Makefiles that we have had before. The Makefiles are still present but will be removed in a future PR
> ci: simplify csi plugin image building pipeline

- docs/cert-manager.md
Closes #215 by adding a piece of documentation explaining how to use cert-manager to automate certificate rotation for the Webhook Server
> docs: add instructions for using cert-manager

- docs/user-guide.md
I was able to test archive datasets now that #367 has been fixed and it looks like having
```yaml
local:
provision: "true" # <---- Required to create a bucket in the backing store
```
causes the following error:
```
An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
```
This PR removes it, ensuring the example works
> fix: remove provision:true as it would cause failures

- examples/templates/example-dataset-s3-provision.yaml
- examples/templates/example-dataset-s3-secrets.yaml
Caused by #146 
Solves #370 
I spent a while struggling with this, since I copied the examples and they weren't entirely applicable :( Hoping this helps others.
> Removed deprecated secret-namespace references from examples

- chart/values.yaml
- release-tools/manifests/dlf-ibm-k8s.yaml
- release-tools/manifests/dlf-ibm-oc.yaml
- release-tools/manifests/dlf-oc.yaml
- release-tools/manifests/dlf.yaml
Fixes #386 
Updates the values in the root Helm chart to the latest from K8s SIG Storage repos
> Updating the root chart to have the latest sidecars for CSI plugins
